title: hy-drawer
email: mail@qwtel.com

description: >
  A touch-enabled drawer component for the modern web.
baseurl: /hy-drawer
url: https://qwtel.com

author:
  email: mail@qwtel.com
  social:
    github: https://github.com/qwtel/hy-drawer
    npm: https://www.npmjs.com/package/hy-drawer
    download: https://github.com/qwtel/hy-drawer/archive/v1.0.0-hydejack.11.zip

copyright: © 2017 Florian Klampfer

permalink: pretty

google_analytics: UA-84025722-3

color: '#4fb1ba'
image:
  background: 'linear-gradient(to bottom,#193747 0%,#233e4c 30%,#3c929e 50%,#d5d5d4 70%,#cdccc8 100%)'
  overlay:    true

# Build settings
markdown: kramdown

plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  # - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-titles-from-headings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - webpack.config.js
  - src
  - scripts
include:
  - LICENSE.md

theme: jekyll-theme-hydejack
# remote_theme: qwtel/hydejack@gem

defaults:
  - scope:
      path: doc/options.md
    values:
      menu: true
      order: 1
  - scope:
      path: doc/methods.md
    values:
      menu: true
      order: 2
  - scope:
      path: doc/events.md
    values:
      menu: true
      order: 3
  - scope:
      path: doc/styling.md
    values:
      menu: true
      order: 4

titles_from_headings:
  strip_title: true
  collections: true

relative_links:
  collections: true

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true

data_social:
  github:
    name: GitHub
    icon: icon-github
  npm:
    name: npm
    icon: icon-npm
  download:
    name: Download
    icon: icon-box-add
