# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: y-drawer
tagline: Why push state?
email: mail@qwtel.com

description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /y-drawer
url: https://qwtel.com
twitter_username: qwtel
github_username:  qwtel

permalink: pretty

color: '#ff6600'
image: data:image/gif;base64,R0lGODlhAQABAPAAAP9mAP///yH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
gems:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-titles-from-headings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js

strip_title: true

defaults:
  - scope:
      path: "LICENSE.md"
    values:
      menu: true
  - scope:
      path: "NOTICE.md"
    values:
      menu: true
